### ISSUE TITLE
Feature Request: Support Flatpak/Appimage/Snap

### ISSUE THREAD

**Issue by dnet890** [Suwayomi/Suwayomi-VaadinUI#82] opened 2023-11-20 10:14 UTC
Hi
Nowadays flatpak/appimage/snap can cover multiple distributions without bound by packaging. Is it possible to support Flatpak/Appimage/Snap?

**Comment by aless2003** [comment] 2023-11-20 12:47
I might, I'll have to look into how they are packaged and how complicated it would be to integrate into the GitHub actions pipeline. I'll get back to this when I get some time

**Comment by aless2003** [comment] 2023-11-23 21:43
So little update on this. I got a (half) working flatpak, though it for sure isn't working as intended. Only runnable through sudo and only installable through the flatpak-builder command (as far as I can tell). But it's progress nonetheless 😅

**Comment by aless2003** [comment] 2023-11-29 23:39
I've gotten a functional version of the flatpak now, not sure yet how I get that on something like flathub yet and if I have to change things for that, but I'll have to read into that and make another update on this

**Comment by aless2003** [comment] 2023-12-04 23:34
Yeah so, I give up. I don't really get how flatpak works when distributing stuff. I manage to get it built, but the flathub linter prints me a bunch of errors. I'll leave this open for anybody who wants to work on this, but I'm probably not the right person for this. I don't really use Linux myself and tried to get this flatpak working for multiple weeks now, so I clearly don't have the expertise needed for this, nor do I really think it's worth the time considering we already have both a dep and rpm release available. I'll leave my flatpak manifest I've written here for anybody wanting to takeover:

```json
{
  "app-id": "online.hatsunemiku.tachidesk-vaadinui",
  "runtime": "org.freedesktop.Platform",
  "runtime-version": "23.08",
  "sdk": "org.freedesktop.Sdk",
  "sdk-extensions": [
    "org.freedesktop.Sdk.Extension.openjdk17"
  ],
  "command": "vaaui.sh",
  "modules": [
    {
      "name": "openjdk",
      "buildsystem": "simple",
      "build-commands": [
        "/usr/lib/sdk/openjdk17/install.sh"
      ]
    },
    {
      "name": "Tachidesk-VaadinUI",
      "buildsystem": "simple",
      "build-commands": [
        "mkdir -p /app/bin",
        "ls",
        "mv Tachidesk-VaadinUI-*.*.*.jar /app/bin/Tachidesk-VaadinUI.jar",
        "install flatpak-start-wrapper.sh /app/bin/vaaui.sh",
        "chmod +x /app/bin/vaaui.sh",
        "install -D -m0644 online.hatsunemiku.tachidesk-vaadinui.desktop /app/online.hatsunemiku.tachidesk-vaadinui.desktop"
      ],
      "sources": [
        {
          "type": "file",
          "url": "https://github.com/Suwayomi/Tachidesk-VaadinUI/releases/download/v1.0.2/Tachidesk-VaadinUI-1.0.2.jar",
          "sha256": "c229fb16a985025a4a30ab6b88faaf7cff349e4bac32f6c25629c2e5a85904e2"
        },
        {
          "type": "file",
          "path": "flatpak-start-wrapper.sh"
        },
        {
          "type": "file",
          "path": "online.hatsunemiku.tachidesk-vaadinui.desktop"
        }
      ]
    }
  ],
  "finish-args": [
    "--env=PATH=/app/jre/bin:/app/bin/",
    "--share=network",
    "--filesystem=home",
    "--socket=wayland",
    "--socket=fallback-x11",
    "--share=ipc"
  ]
}
```

Here's the desktop file I made (which never seemed to show up for me)
```desktop
[Desktop Entry]
Encoding=UTF-8
version=1.0.1
Type=Application
Terminal=false
Exec=/usr/bin/flatpak run online.hatsunemiku.tachidesk-vaadinui
Keywords=Tachidesk;Manga;
Categories=Viewer;
Name=Tachidesk VaadinUI
```

And lastly the script to run the whole thing:
```bash
#!/usr/bin/bash
java -jar /app/bin/Tachidesk-VaadinUI.jar
```


All of this probably looks dead stupid to somebody who's using Linux, but it's the best I got. Feel free to ping me for questions about the project in itself though 😊
And sorry again for not being able to do this one. Really tried, but it's just not really my world 😅

**Comment by dtantono** [comment] 2023-12-06 08:43
@aless2003 have you ever tried other agnostic package manager such as Appimage or snap?

**Comment by aless2003** [comment] 2023-12-06 09:30
> @aless2003 have you ever tried other agnostic package manager such as Appimage or snap?

I have tried to do a snap, not sure quite yet sure on that one. I think there was some issue with the Java version of the snap base image and Gradle. Can't remember though. I might do another try on that one if I get the time. Unfortunately I'm relatively busy at the moment so learning new packaging formats is a relatively big chore right now. AppImage I'm not remotely sure how it works and couldn't really get into it at all. I've only heard about it maybe twice in 4 years, so I wanted to try the popular options first.
I would likely need somebody for actually understanding what I'm doing though. I mostly guessed on the flatpak, because I found the documentation relatively hard to navigate effectively.

**Comment by razzeee** [comment] 2023-12-06 15:54
The used app id doesn't seem correct `online.hatsunemiku.tachidesk-vaadinui` or do you own `hatsunemiku.online`? Is there any other project website, or should it use github as source for the id?

**Comment by razzeee** [comment] 2023-12-06 15:59
Also is there an appdata file or should that also be written for this? See for example https://github.com/flathub/net.filebot.FileBot/blob/master/net.filebot.FileBot.appdata.xml

Specs are here https://www.freedesktop.org/software/appstream/docs/

**Comment by aless2003** [comment] 2023-12-06 17:45
> The used app id doesn't seem correct `online.hatsunemiku.tachidesk-vaadinui` or do you own `hatsunemiku.online`? Is there any other project website, or should it use github as source for the id?

I own hatsune-miku.online, but it doesn't allow that 😅
I also just used the same reverse domain setup I used in gradle when creating the actual project. I never actually thought it would gain any attention to be honest 😅
Additionally it was mostly for testing whether I could get this done. I planned to migrate over to diamondmiku.com which I also own, should it have worked. Feel free to go with whatever you like though if you want to create a flatpak for this

**Comment by razzeee** [comment] 2023-12-06 18:57
It compiles fine for me but crashes on start, probably due to permissions. Not sure when I have time again.

Regarding the app ID as far as I know you can substitute - with _

**Comment by aless2003** [comment] 2023-12-06 22:58
So I could validate one thing now, the VM I used is utterly broken. Not sure if it's the flatpak install or the Distro as a whole, but spinning up a new VM made it compile fine. Not what I expected to be wrong, but you live you learn I guess 😅
I can definitely see bugs with running it that way, but I think I can fix those relatively easy. Really want to thank you for helping me out here, I was actually just done with it 😅

**Comment by razzeee** [comment] 2023-12-06 23:15
Let me know, if you need any more help

**Comment by razzeee** [comment] 2023-12-24 23:07
Hard to tell without seeing the code, but I've used the .sh as an entry point see https://github.com/razzeee/online.hatsune_miku.tachidesk-vaadinui/blob/main/tachidesk-vaadinui.sh

If upstream provides a desktop file rewriting it via `rename-desktop-file` see https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html might be helpful (it expects the name of the desktop file to rename)

**Comment by aless2003** [comment] 2023-12-24 23:43
> Hard to tell without seeing the code, but I've used the .sh as an entry point see https://github.com/razzeee/online.hatsune_miku.tachidesk-vaadinui/blob/main/tachidesk-vaadinui.sh

Here's the Desktop file I currently have. And I assumed that the vaaui.sh part would point to the one inside flatpak. 
```
[Desktop Entry]
Name=Tachidesk VaadinUI
Exec=vaaui.sh
Type=Application
Terminal=false
Keywords=Tachidesk;Manga;
Categories=Viewer;Graphics;
Icon=online.hatsune_miku.tachidesk-vaadinui
```

If you need a bit more info, I got the repository where I currently try to get this done here: https://github.com/aless2003/online.hatsune_miku.tachidesk-vaadinui/tree/main

> If upstream provides a desktop file rewriting it via `rename-desktop-file` see https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html might be helpful (it expects the name of the desktop file to rename)
Correct me if I'm wrong, but I think that one just renames the name of the desktop file, rather than rewriting its contents

**Comment by razzeee** [comment] 2023-12-25 01:26
Did you try it like I did here? https://github.com/razzeee/online.hatsune_miku.tachidesk-vaadinui/blob/main/online.hatsune_miku.tachidesk-vaadinui.desktop#L6

**Comment by aless2003** [comment] 2023-12-25 02:30
So uh, correction, seems like that's actually coming from the flatpak itself rather than the desktop file. I somehow managed to get the flatpak to not recognize the executable/launch script anymore :/
Gonna have to investigate that 😅

**Comment by razzeee** [comment] 2023-12-25 02:43
I've checked out your branch and build it, it seems to work fine, but you should probably set `Terminal=true` in the .desktop file, at least if I understoood that application correctly

**Comment by aless2003** [comment] 2023-12-25 02:47
it builds, yeah, but it doesn't run (at least my build isn't). It always tells me that it can't find "vaaui.sh", which is the command I specified in the flatpak manifest

**Comment by razzeee** [comment] 2023-12-25 02:55
It runs fine for me, are you using the commands from the readme?

**Comment by aless2003** [comment] 2023-12-25 02:56
I do, yeah

**Comment by aless2003** [comment] 2023-12-25 03:08
Ok, so uh interesting development. It runs... but only when I submit it to GitHub and pull it down again. I've got no idea what the issue there might be, but it probably means I did a stupid thing somewhere along the way. Oh well, will investigate this further tomorrow/today, as it is 4 am. But thanks for your help, this made me realize something's wrong with my local stuff... again.

**Comment by aless2003** [comment] 2023-12-29 15:56
I've now started a pull request for flathub and am currently in the process of adding/changing some stuff to get it merged. Just as a little update @dtantono

**Comment by aless2003** [comment] 2024-02-14 21:34
@dtantono This should now be available at flathub. To install run flatpak `flatpak install online.hatsune_miku.tachidesk-vaadinui`
I'm happy I've gotten this dealt with. Will maybe pick Snap back up at some point in the future, however, not anytime soon, so I'll close this issue here.

@razzeee Thank you very much for your help with this. I swear I wouldn't have gotten through this without you! 

Have a nice day people and if any bugs should arise, don't hesitate to open another issue

**Closed as completed by aless2003** 2024-02-14 21:34 UTC
Labels: enhancement
